package vcmsa.projects.prog7314.data.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/*
    Code Attribution for: Room DB Entities
    ===================================================
    Android Developers, 2020. Defining data using Room entities | Android Developers (Version unknown) [Source code].
    Available at: <https://developer.android.com/training/data-storage/room/defining-data>
    [Accessed 18 November 2025].
*/

@Entity(
    tableName = "level_progress",
    // Link each level progress record to a specific user.
    // Deleting the user removes all their level progress.
    foreignKeys = [
        ForeignKey(
            entity = UserProfileEntity::class,
            parentColumns = ["userId"],
            childColumns = ["userId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    // Ensure that each user has only one record per level.
    indices = [Index(value = ["userId", "levelNumber"], unique = true)]
)
data class LevelProgressEntity(

    // Unique ID for this level progress record.
    // Automatically generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // The user this level progress belongs to.
    val userId: String,

    // Level number (e.g., 1-16).
    val levelNumber: Int,

    // Stars earned for this level (0-3).
    val stars: Int = 0,

    // Highest score achieved for this level.
    val bestScore: Int = 0,

    // Fastest time achieved for this level, in seconds.
    val bestTime: Int = 0,

    // Fewest moves taken to complete this level.
    val bestMoves: Int = 0,

    // Indicates if the level has been unlocked.
    val isUnlocked: Boolean = false,

    // Indicates if the level has been completed.
    val isCompleted: Boolean = false,

    // Timestamp of the last time this level was played.
    val lastPlayed: Long = 0,

    // Number of times the user has played this level.
    val timesPlayed: Int = 0,

    // Whether this progress record has been synced to the server.
    val isSynced: Boolean = false,

    // Timestamp of the last update to this record.
    val updatedAt: Long = System.currentTimeMillis()
)
