name: Android CI - Unit Tests
 
on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

  workflow_dispatch:
 
jobs:

  test:

    name: Run Unit Tests

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v4
 
      - name: Set up JDK 17

        uses: actions/setup-java@v4

        with:

          distribution: 'temurin'

          java-version: '17'

          cache: 'gradle'
 
      - name: Grant execute permission for gradlew

        run: chmod +x ./gradlew
 
      - name: Run unit tests

        run: ./gradlew testDebugUnitTest --stacktrace
 
      - name: Upload test results

        if: always()

        uses: actions/upload-artifact@v3

        with:

          name: test-results

          path: app/build/reports/tests/testDebugUnitTest/
 
