name: Android CI - Memory Match Madness
 
on:

  push:

    branches: [ "master", "main", "develop" ]

  pull_request:

    branches: [ "master", "main", "develop" ]

  workflow_dispatch:
 
jobs:

  build:

    name: Build and Test

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout code

        uses: actions/checkout@v4
 
      - name: Set up JDK 17

        uses: actions/setup-java@v4

        with:

          distribution: 'temurin'

          java-version: '17'

          cache: 'gradle'
 
      - name: Grant execute permission for gradlew

        run: chmod +x ./gradlew
 
      - name: Build with Gradle

        run: ./gradlew build --stacktrace
 
      - name: Run unit tests

        run: ./gradlew testDebugUnitTest --stacktrace
 
      - name: Display test results

        if: always()

        run: |

          echo "Test Results:"

          cat app/build/test-results/testDebugUnitTest/*.xml || echo "No test results found"
 
